##########################################
# Pipeline seedvicious - YAML configuration #
##########################################

# See syntax at: https://yaml.org/start.html

input:
  
  transcripts: "/path/file"
  
  micrornas: "/path/file"
